name: Build VGPU

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile VGPU
      run: make -C src/gl

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VgpuLib
        path: src/gl/*.so
